# Generated by Django 3.2.9 on 2023-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0008_auto_20230302_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menorandum',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
