# Generated by Django 3.2.9 on 2023-04-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0009_alter_menorandum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menorandum',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
