# Generated by Django 3.2.9 on 2023-04-11 15:27

from django.db import migrations, models
import memorandum.models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0010_alter_menorandum_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archivos', models.FileField(blank=True, null=True, upload_to=memorandum.models.user_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='menorandum',
            name='archivos',
        ),
        migrations.AddField(
            model_name='menorandum',
            name='archivos',
            field=models.ManyToManyField(to='memorandum.Archivos'),
        ),
    ]
