# Generated by Django 3.2.9 on 2023-04-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0012_archivos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='memo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='memorandum.menorandum'),
        ),
    ]
