# Generated by Django 3.2.9 on 2023-04-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0013_archivos_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='memo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='memorandum.menorandum'),
        ),
    ]
