# Generated by Django 3.2.9 on 2023-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0014_alter_archivos_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='memo',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre del Memorandum'),
        ),
    ]
