# Generated by Django 3.2.9 on 2023-05-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0016_alter_menorandum_date_expiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menorandum',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='menorandum',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
    ]
