# Generated by Django 3.2.9 on 2023-05-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0018_destinatarios_invitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatarios',
            name='nombre_memo',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre del Memorandum'),
        ),
    ]
