# Generated by Django 3.2.9 on 2023-05-26 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memorandum', '0019_destinatarios_nombre_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatarios',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
