# Generated by Django 3.2.9 on 2023-05-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0021_alter_destinatarios_destinatario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinatarios',
            options={'verbose_name': 'Destinatario', 'verbose_name_plural': 'Destinatarios'},
        ),
        migrations.AlterModelOptions(
            name='invitacion',
            options={'verbose_name': 'Invitacion', 'verbose_name_plural': 'Invitaciones'},
        ),
    ]
