# Generated by Django 3.2.9 on 2023-05-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandum', '0022_auto_20230528_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menorandum',
            name='date_expiring',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
    ]
